port: 8089
client_id: kuaihe-mp-test
client_secret: xf6y7AqYSd22wYhrOScm3ovKHOVn6itN
eureka_address: https://gateway-eureka-test.19k8s.cn/eureka # eureka地址
auth_address: https://auth-test.dw.19k8s.com # auth地址
process_authorization_seconds: 180
authorization_fresh: 7000
